### PR TITLE
New article on Pull Request Challange!

### PR DESCRIPTION
**Pull request by kyzn**
Let me know if you want me to update anything. Thanks a lot!

### CODE REVIEW

**Comment by dnmfarrell** [comment]
First glance, this looks ... awesome :tada:! I'll review but we should get this live this week

**Comment by kyzn** [comment]
Great news! Thanks David.

**Comment by dnmfarrell** [comment]
Hey @kyzn thanks a lot for this. I've reviewed the text and opened a new [branch](https://github.com/dnmfarrell/perldotcom/tree/kyzn-why-join-prc) with my suggested edits as new commits.:

- f0ee5ff795ceaa4aadefd24974398d9f41e04c63
- 756f1f1734bf86b932290841227969394ded60d9
- 46500a763f8b0b71d0a3e5e273a4bdddba6c6f44
- 161a65d646096793c7f030e2bf160d07efea4a53
- ddfac37322f2e59ada60f4791a8321ffce37d16c

Happy to discuss any of the changes further if you like. If you're happy with the changes I'll publish it, else we can finesse together. See what you think!

**Comment by kyzn** [comment]
Hi David! This is **AWESOME**! Thanks a lot for your editing work! I pulled your commits into my branch, and added a few commits myself. I also left the very same changes as comments. Let me know what you think!

Couple questions:
- Should I add your name as the editor? I truly appreciate your work!
- Can I use the edited copy in my own blog? Would definitely attribute edtior there 😃 
- (For future) Can I _also_ translate this into other languages with the same attribution?

Thanks again!

**Comment by dnmfarrell** [comment]
Hey @kyzn these edits look good, thank you - I suppose two editors are better than one :smile: 

Absolutely feel free to re-post on your blog and/or translate and post elsewhere. For the blog post, would you mind including a link back to the article on Perl.com saying "originally posted on Perl.com" or "cross posted from Perl.com" something like that?

Thank you for offering me attribution, I appreciate it but that's not necessary; it's really your content I just shuffled it around a bit.

**Comment by kyzn** [comment]
Thanks again @dnmfarrell! Published at https://kyzn.org/2018-01-22-why-should-you-join-cpan-prc.html too 👍
I will link to my blog in bio next time 🙂

**Pull request merged**
