### PR TITLE
Patch originally created by @kyzn. I needed this to get the site up locally.

### PR DESCRIPTION
**Pull request by manwar**
Hi @briandfoy 

Please review the PR.
Original patch created by @kyzn as below:
https://github.com/kyzn/perldotcom/commit/e19e5fa6

Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by manwar** [comment]
Honestly speaking, I don't either. However it did solve the issue I had. 
May be @kyzn can explain this better?

**Comment by dnmfarrell** [comment]
Guessing what these do:
* `content/legacy/_pub_2004_04_08_bloom_filters.md` just shortens an article description. I've pushed a commit which does the same. We probably have loads of legacy articles that need their description trimmed / re-written. We could create a ticket for that
* `layouts/partials/header/ograph-twittercard.html` converts the twittercard  image URL into a URI by removing the scheme and domain. I'm not sure why that's required, it's not the [standard](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary) and the card is populating correctly I think? [example](view-source:https://www.perl.com/article/xs-utility-routines-that-are-good-to-know/).
* `layouts/shortcodes/mcpan.html` I don't know why this should be deleted, we use it in many different articles. This creates the "short code" `{{< mcpan "Data::Dumper" >}}` to build a link to metacpan. I drafted an article which used the `cpan` shortcode incorrectly, which would have warned when launching the server, but I've fixed that now (`s/cpan/mcpan/`).

**Comment by dnmfarrell** [comment]
I'm not sure why these are required to build the site @manwar did you tryu `hugo server` and got an exception? The version of hugo I'm using is:

    $ hugo version
    Hugo Static Site Generator v0.31.1 linux/amd64 BuildDate: 2017-11-27T06:26:24-05:00`

**Comment by kyzn** [comment]
It has been a while since I wrote the patch, but here's what I remember:

- `_pub_2004_04_08_bloom_filters.md`: A character in description, likely `{ }`, was breaking markdown to html 
- `ograph-twittercard.html `: There was an error about `strings` being missing? Just like @manwar posted here: https://twitter.com/cpan_author/status/991732122430988289
- `layouts/shortcodes/mcpan.html`: No idea..

I agree that we have to find out what was breaking my & @manwar's hugo from starting before applying any changes. I'll add more details tonight.

**Comment by dnmfarrell** [comment]
Sounds good, thanks!

**Comment by kyzn** [comment]
I found the answer [here](https://stackoverflow.com/questions/45120648/function-jsonify-not-defined-error-while-trying-to-deploy-in-hugo#45268688): problem was hugo's version.

Previously I was using hugo that was installed with `sudo apt-get install hugo`. I went [here](https://github.com/gohugoio/hugo/releases) and installed the latest version, and errors went away.

This was the previous version:

    Hugo Static Site Generator v0.16-DEV BuildDate: 2016-02-06T09:14:17-08:00

This is the latest version:

    Hugo Static Site Generator v0.40.2 linux/amd64 BuildDate: 2018-04-30T06:47:44Z

For the record, these were the error messages:

    ERROR: 2018/05/02 19:33:43 template.go:350: template: partials/header/ograph-twittercard.html:12: function "strings" not defined
    ERROR: 2018/05/02 19:33:43 shortcode.go:533: error processing shortcode shortcodes/mcpan.html
     ERR: template: shortcodes/mcpan.html:1:55: executing "shortcodes/mcpan.html" at <index .Params 1>: error calling index: index out of range: 1
    ERROR: 2018/05/02 19:33:43 shortcode.go:533: error processing shortcode shortcodes/mcpan.html
     ERR: template: shortcodes/mcpan.html:1:55: executing "shortcodes/mcpan.html" at <index .Params 1>: error calling index: index out of range: 1
    ERROR: 2018/05/02 19:34:09 template.go:119: html/template: "partials/header/ograph-twittercard.html" is an incomplete template in partials/header/ograph-twittercard.html

I'm going to suggest adding a note to Contributing file saying "get the latest version, get it from here, don't apt-get install" etc.

**Comment by dnmfarrell** [comment]
Thanks for confirming the issue @kyzn, that's a good suggestion.

@manwar I think we can close this PR?

**Comment by manwar** [comment]
Certainly this can be closed. Thanks everyone for the help.

**Pull request closed without merging**
