### PR TITLE
Patch legacy article 10

### PR DESCRIPTION
**Pull request by manwar**
Hi @briandfoy 

Please review the PR.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by briandfoy** [comment]
content/legacy/_pub_2003_04_22_pool.md has version specific links. Can you fix those?

**Comment by manwar** [comment]
Hi @briandfoy 

Pushed the changes. Please review it.

Many Thanks.
Best Regards,
Mohammad S Anwar

**Comment by briandfoy** [comment]
I still see version-specific links in your new change.

**Comment by manwar** [comment]
Is this OK, now?
Sorry for the inconvenience.

**Comment by briandfoy** [comment]
Much better! Thanks,

**Pull request merged**
