### PR TITLE
Edits for the setup for PRC article

### PR DESCRIPTION
**Pull request by dnmfarrell**
- s/OSX/macOS/ - I think that's the proper name now
- Add more links to metacpan
- Format terminal commands as if they're run on the terminal
- Break things out of bullet points into text paragraphs
- Explain a few things a little bit more
- A few minor grammar edits, fact corrections (e.g. s/Most/Many/ when
    referring to dzil, as we really don't know)
- Use --- as a horizontal line break, to avoid italicizing formatting
error in text editor :-)

### CODE REVIEW

**Comment by kyzn** [comment]
Hi David! Thanks a lot for your editing work, this is amazing! :tada:  I have a couple comments, let me know if it makes sense:
- In header, it seems I had reintroduced the "thumbanail" typo: https://github.com/kyzn/perldotcom/commit/b04a1386a8621479498920c2603861e67ec69579
- Add a few missing words back (which & dzil): https://github.com/kyzn/perldotcom/commit/cc51d257b4c2ac779eced7101f06646326c17ee1
- (Not so important) Lowercase `nano`: https://github.com/kyzn/perldotcom/commit/dc73329b625eb56eb8f4f69d257b227bbc50b7a1
- Mention that with docker image, they can still use local text editor. This was slightly important, as some prefer to use Sublime: https://github.com/kyzn/perldotcom/commit/961951abc2771ab7b5180029b8c0d34c80de2d81

If you think these are good, feel free to either pull them to your branch, or we can create a new PR out of https://github.com/kyzn/perldotcom/commits/kivanc-setup-computer-cpan-prc, which is based off of your branch.


Also: I had some HTML problems on my local checkout.
- I couldn't get `<code></code>` tags working, and
- at one instance, list items did not seem to add newline.



Do you think these are local-only issues?

Thanks again!

**Comment by dnmfarrell** [comment]
@kyzn nice catches, thanks :D I've made the edits manually. If you spot nay other changes needed, just let me know :+1:

**Comment by kyzn** [comment]
Thanks a lot!

**Comment by dnmfarrell** [comment]
And we're live https://www.perl.com/article/setup-your-computer-for-cpan-prc/ !

**Comment by kyzn** [comment]
That was fast, thanks @dnmfarrell! One [minor] thing I noticed is that, the date seems to be 2/20. Do you think it's worth a commit to update that?

**Comment by dnmfarrell** [comment]
Oh good point - man, I really need a "release check tool". WIll fix

**Pull request merged**
